use std::{
    path::{Path, PathBuf},
    sync::Arc,
};

use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};
use warpui::{AppContext, ModelContext};

use crate::{
    code_review::diff_size_limits::DiffSize,
    util::git::{Commit, PrInfo},
};

#[derive(Clone, Debug, PartialEq)]
pub struct UnifiedDiffHeader {
    pub old_start_line: usize,
    pub old_line_count: usize,
    pub new_start_line: usize,
    pub new_line_count: usize,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum GitFileStatus {
    New,
    Modified,
    Deleted,
    Renamed { old_path: String },
    Copied { old_path: String },
    Untracked,
    Conflicted,
}

impl GitFileStatus {
    pub fn is_renamed(&self) -> bool {
        matches!(self, Self::Renamed { .. })
    }

    pub fn is_new_file(&self) -> bool {
        matches!(self, Self::New | Self::Untracked)
    }
}

impl TryFrom<&str> for GitFileStatus {
    type Error = anyhow::Error;

    fn try_from(_status_code: &str) -> Result<Self> {
        Ok(Self::Modified)
    }
}

#[derive(Clone, Debug)]
pub struct FileStatusInfo {
    pub path: PathBuf,
    pub status: GitFileStatus,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiffLine {
    pub line_type: DiffLineType,
    pub old_line_number: Option<usize>,
    pub new_line_number: Option<usize>,
    pub text: String,
    pub no_trailing_newline: bool,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum DiffLineType {
    Context,
    Add,
    Delete,
    HunkHeader,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiffHunk {
    pub old_start_line: usize,
    pub old_line_count: usize,
    pub new_start_line: usize,
    pub new_line_count: usize,
    pub lines: Vec<DiffLine>,
    pub unified_diff_start: usize,
    pub unified_diff_end: usize,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileDiff {
    pub file_path: PathBuf,
    pub status: GitFileStatus,
    pub hunks: Arc<Vec<DiffHunk>>,
    pub is_binary: bool,
    pub is_autogenerated: bool,
    pub max_line_number: usize,
    pub has_hidden_bidi_chars: bool,
    pub size: DiffSize,
}

impl FileDiff {
    pub fn is_empty(&self) -> bool {
        self.additions() == 0 && self.deletions() == 0
    }

    pub fn additions(&self) -> usize {
        self.hunks
            .iter()
            .flat_map(|hunk| &hunk.lines)
            .filter(|line| line.line_type == DiffLineType::Add)
            .count()
    }

    pub fn deletions(&self) -> usize {
        self.hunks
            .iter()
            .flat_map(|hunk| &hunk.lines)
            .filter(|line| line.line_type == DiffLineType::Delete)
            .count()
    }
}

#[derive(Debug)]
pub struct FileDiffAndContent {
    pub file_diff: FileDiff,
    pub content_at_head: Option<String>,
}

#[derive(Debug)]
pub struct GitDiffWithBaseContent {
    pub files: Vec<FileDiffAndContent>,
    pub total_additions: usize,
    pub total_deletions: usize,
    pub files_changed: usize,
}

#[derive(Clone)]
pub struct GitDiffData {
    pub files: Vec<FileDiff>,
    pub total_additions: usize,
    pub total_deletions: usize,
    pub files_changed: usize,
}

impl GitDiffData {
    pub fn is_dirty(&self) -> bool {
        self.total_additions + self.total_deletions + self.files_changed > 0
    }
}

impl From<GitDiffWithBaseContent> for GitDiffData {
    fn from(value: GitDiffWithBaseContent) -> Self {
        Self {
            files: value.files.into_iter().map(|file| file.file_diff).collect(),
            total_additions: value.total_additions,
            total_deletions: value.total_deletions,
            files_changed: value.files_changed,
        }
    }
}

impl From<&GitDiffWithBaseContent> for GitDiffData {
    fn from(value: &GitDiffWithBaseContent) -> Self {
        Self {
            files: value
                .files
                .iter()
                .map(|file| file.file_diff.clone())
                .collect(),
            total_additions: value.total_additions,
            total_deletions: value.total_deletions,
            files_changed: value.files_changed,
        }
    }
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum GitDeltaPreference {
    Always,
    OnlyDirty,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash, Default, Serialize)]
pub enum DiffMode {
    #[default]
    Head,
    MainBranch,
    OtherBranch(#[serde(skip_serializing)] String),
}

impl DiffMode {
    pub fn from_branch(branch: &str, main_branch_name: Option<&str>) -> Self {
        if main_branch_name == Some(branch) {
            Self::MainBranch
        } else {
            Self::OtherBranch(branch.to_string())
        }
    }
}

pub enum DiffState {
    NotInRepository,
    Loading,
    Error(String),
    Loaded(GitDiffData),
}

#[derive(Default, Debug)]
pub struct DiffMetadataAgainstBase {
    pub(super) aggregate_stats: DiffStats,
}

impl DiffMetadataAgainstBase {
    pub fn is_dirty(&self) -> bool {
        !self.aggregate_stats.has_no_changes()
    }
}

#[derive(Default)]
pub struct DiffStateModel {
    repo_path: Option<PathBuf>,
    mode: DiffMode,
    metadata: Option<DiffMetadata>,
}

#[derive(Default)]
struct DiffMetadata {
    main_branch_name: String,
    current_branch_name: String,
    against_head: DiffMetadataAgainstBase,
    against_base_branch: Option<DiffMetadataAgainstBase>,
}

#[derive(Debug, Copy, Clone, Default)]
pub struct DiffStats {
    pub files_changed: usize,
    pub total_additions: usize,
    pub total_deletions: usize,
}

impl DiffStats {
    pub(crate) fn has_no_changes(&self) -> bool {
        self.files_changed == 0
    }
}

#[derive(Debug, Clone)]
pub struct GitDiffInfo {
    pub uncommitted_stats: Option<DiffStats>,
    pub main_branch_stats: Option<DiffStats>,
    pub main_branch_name: Option<String>,
}

impl DiffStateModel {
    pub fn new(repo_path: Option<String>, _ctx: &mut ModelContext<Self>) -> Self {
        Self {
            repo_path: repo_path.map(PathBuf::from),
            mode: DiffMode::default(),
            metadata: None,
        }
    }

    pub fn maybe_set_new_active_repository(
        &mut self,
        repo_path: Option<String>,
        _ctx: &mut ModelContext<Self>,
    ) {
        self.repo_path = repo_path.map(PathBuf::from);
    }

    pub fn get(&self) -> DiffState {
        DiffState::NotInRepository
    }

    pub fn get_metadata(&self) -> Option<&DiffMetadataAgainstBase> {
        None
    }

    pub fn diff_mode(&self) -> DiffMode {
        self.mode.clone()
    }

    pub fn get_uncommitted_stats(&self) -> Option<DiffStats> {
        None
    }

    pub fn get_main_branch_stats(&self) -> Option<DiffStats> {
        None
    }

    pub fn get_main_branch_name(&self) -> Option<String> {
        self.metadata
            .as_ref()
            .map(|metadata| metadata.main_branch_name.clone())
    }

    pub fn diff_mode_for_base_branch(&self, base_branch: Option<&str>) -> DiffMode {
        base_branch
            .map(|branch| DiffMode::from_branch(branch, self.get_main_branch_name().as_deref()))
            .unwrap_or(DiffMode::MainBranch)
    }

    pub fn get_current_branch_name(&self) -> Option<String> {
        self.metadata
            .as_ref()
            .map(|metadata| metadata.current_branch_name.clone())
    }

    pub fn is_on_main_branch(&self) -> bool {
        false
    }

    pub fn unpushed_commits(&self) -> &[Commit] {
        &[]
    }

    pub fn upstream_ref(&self) -> Option<&str> {
        None
    }

    pub fn upstream_differs_from_main(&self) -> bool {
        false
    }

    pub fn pr_info(&self) -> Option<&PrInfo> {
        None
    }

    pub fn is_pr_info_refreshing(&self) -> bool {
        false
    }

    pub fn is_git_operation_blocked(&self, _app: &AppContext) -> bool {
        false
    }

    pub fn get_diff_stats(&self) -> GitDiffInfo {
        GitDiffInfo {
            uncommitted_stats: None,
            main_branch_stats: None,
            main_branch_name: self.get_main_branch_name(),
        }
    }

    pub fn get_stats_for_current_mode(&self) -> Option<DiffStats> {
        self.get_stats_for_mode(self.mode.clone())
    }

    pub fn get_stats_for_mode(&self, _mode: DiffMode) -> Option<DiffStats> {
        None
    }

    pub fn has_head(&self) -> bool {
        false
    }

    pub fn active_repository_path(&self, _app: &AppContext) -> Option<PathBuf> {
        self.repo_path.clone()
    }

    pub fn is_inside_repository(&self) -> bool {
        self.repo_path.is_some()
    }

    pub fn set_diff_mode(
        &mut self,
        mode: DiffMode,
        _should_fetch_base: bool,
        ctx: &mut ModelContext<Self>,
    ) {
        self.mode = mode;
        ctx.emit(DiffStateModelEvent::DiffModeChanged {
            should_fetch_base: false,
        });
    }

    pub fn set_diff_mode_and_fetch_base(&mut self, mode: DiffMode, ctx: &mut ModelContext<Self>) {
        self.set_diff_mode(mode, false, ctx);
    }

    pub fn load_diffs_for_current_repo(&mut self, _ctx: &mut ModelContext<Self>) {}

    pub fn discard_files(
        &mut self,
        _file_infos: Vec<FileStatusInfo>,
        _ctx: &mut ModelContext<Self>,
    ) {
    }

    pub fn set_code_review_metadata_refresh_enabled(
        &mut self,
        _enabled: bool,
        _ctx: &mut ModelContext<Self>,
    ) {
    }

    pub fn refresh_diff_metadata_for_current_repo(&mut self, _ctx: &mut ModelContext<Self>) {}

    pub fn set_active_repository(
        &mut self,
        repo_path: Option<PathBuf>,
        _ctx: &mut ModelContext<Self>,
    ) {
        self.repo_path = repo_path;
    }

    pub fn stop_active_watcher(&mut self, _ctx: &mut ModelContext<Self>) {}

    pub fn remove_active_repo(&mut self, ctx: &mut ModelContext<Self>) {
        self.repo_path = None;
        ctx.emit(DiffStateModelEvent::RepositoryChanged);
    }

    pub fn get_diff_data_for_mode(
        &self,
        _mode: DiffMode,
        _repo_path: PathBuf,
    ) -> impl std::future::Future<Output = Option<GitDiffData>> {
        async { None }
    }

    pub async fn load_diff_data_for_mode(
        _mode: DiffMode,
        _repo_path: PathBuf,
    ) -> Option<GitDiffData> {
        None
    }

    pub async fn compute_merge_base(_repo_path: &Path, _diff_mode: &DiffMode) -> Result<String> {
        anyhow::bail!("git diff state is not available in this build")
    }

    pub async fn diff_metadata_against_head(_repo_path: &Path) -> Result<DiffMetadataAgainstBase> {
        Ok(DiffMetadataAgainstBase::default())
    }

    pub async fn get_all_branches(
        _repo_path: &Path,
        _main_branch: Option<String>,
        _include_remotes: bool,
    ) -> Result<Vec<(String, bool)>> {
        Ok(Vec::new())
    }

    pub async fn get_all_branches_with_known_main(
        _repo_path: &Path,
        _main_branch: String,
        _current_branch: Option<String>,
        _include_remotes: bool,
    ) -> Result<Vec<(String, bool)>> {
        Ok(Vec::new())
    }

    pub fn sort_branches_main_first(
        branches: &[(String, bool)],
    ) -> impl Iterator<Item = &(String, bool)> {
        branches.iter()
    }

    pub fn label_text(&self, mode: DiffMode) -> String {
        match mode {
            DiffMode::Head => "Uncommitted changes".to_string(),
            DiffMode::MainBranch => "Changes vs. main".to_string(),
            DiffMode::OtherBranch(branch) => format!("Changes vs. {branch}"),
        }
    }

    pub fn refresh_pr_info(&mut self, _ctx: &mut ModelContext<Self>) {}

    pub(crate) fn parse_range(range_str: &str) -> Result<(usize, usize)> {
        if let Some(comma_pos) = range_str.find(',') {
            let start: usize = range_str[..comma_pos]
                .parse()
                .map_err(|_| anyhow!("Invalid range start: {}", range_str))?;
            let count: usize = range_str[comma_pos + 1..]
                .parse()
                .map_err(|_| anyhow!("Invalid range count: {}", range_str))?;
            Ok((start, count))
        } else {
            let start: usize = range_str
                .parse()
                .map_err(|_| anyhow!("Invalid range: {}", range_str))?;
            Ok((start, 1))
        }
    }

    pub(crate) fn parse_unified_diff_header(header_line: &str) -> Result<UnifiedDiffHeader> {
        if !header_line.starts_with("@@") {
            anyhow::bail!("Invalid unified diff header: {}", header_line);
        }

        let header_parts: Vec<&str> = header_line.split_whitespace().take(3).collect();
        if header_parts.len() < 3 {
            anyhow::bail!("Invalid unified diff header format: {}", header_line);
        }

        let old_range = &header_parts[1][1..];
        let new_range = &header_parts[2][1..];

        let (old_start_line, old_line_count) = Self::parse_range(old_range)?;
        let (new_start_line, new_line_count) = Self::parse_range(new_range)?;

        Ok(UnifiedDiffHeader {
            old_start_line,
            old_line_count,
            new_start_line,
            new_line_count,
        })
    }
}

#[derive(Debug)]
pub enum InvalidationBehavior {
    All(InvalidationSource),
    AllLockedIndex,
    Files(Vec<PathBuf>),
    PromptRefresh,
}

#[derive(Debug)]
pub enum InvalidationSource {
    MetadataChange,
    IndexLockChange,
}

#[derive(Debug)]
pub enum DiffStateModelEvent {
    RepositoryChanged,
    CurrentBranchChanged,
    DiffMetadataChanged(InvalidationBehavior),
    NewDiffsComputed(Option<GitDiffWithBaseContent>),
    DiffModeChanged { should_fetch_base: bool },
}

impl warpui::Entity for DiffStateModel {
    type Event = DiffStateModelEvent;
}
